---

- name: "Restart Networking networkd"
  shell: |
    systemctl restart systemd-udev-trigger
    networkctl reload
    systemctl is-active frr && systemctl restart frr || true
  async: 60
  poll: 0
  throttle: 1
  when: ansible_os_family == 'Debian'

- name: "Restart Networking NetworkManager"
  shell: |
    nmcli con reload
    systemctl restart NetworkManager
    systemctl is-active frr && systemctl restart frr || true
  async: 60
  poll: 0
  throttle: 1
  when: ansible_os_family == 'RedHat'


- name: "Wait for the system to come back online"
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 60

- name: "Refresh facts"
  ansible.builtin.setup:
    gather_subset:
      - network
