---

- name: "Restart Networking"
  shell: |
    systemctl restart systemd-udev-trigger
    networkctl reload
    systemctl is-active frr && systemctl restart frr || true
  async: 60
  poll: 0
  throttle: 1

- name: "Wait for the system to come back online"
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 60

- name: "Refresh facts"
  ansible.builtin.setup:
    gather_subset:
      - network
